### ISSUE TITLE
Differing versions of OpenZeppelin contracts due to misplacement of package.json file

### ISSUE THREAD

**Issue by escottalexander** [Paul-Sizon/rootstock-extention#1]
You are importing OZ/contracts in the main package.json for the monorepo. I think you meant to put it under the hardhat directory. For me, I get errors when deploying due to different OZ contracts. Default oz/contracts version in se2 right now seems to be 4.8.1 and you are trying to use 5.0.2 but as I said it is not being installed correctly when I use the extension.
```
[elliott@fedora rootstock]$ yarn deploy
Downloading compiler 0.8.24
TypeError: Wrong argument count for modifier invocation: 1 arguments given but expected 0.
  --> contracts/RuneToken.sol:31:51:
   |
31 |     constructor(address initialOwner) ERC1155("") Ownable(initialOwner) {}
   |                                                   ^^^^^^^^^^^^^^^^^^^^^


Error HH600: Compilation failed

For more info go to https://hardhat.org/HH600 or run Hardhat with --show-stack-traces
```

I also had to adjust the solidity compiler version to 0.8.24 in the hardhat config to avoid getting this error:
```
Error HH606: The project cannot be compiled, see reasons below.

The Solidity version pragma statement in these files doesn't match any of the configured compilers in your config. Change the pragma or configure additional compiler versions in your hardhat config.

  * contracts/RuneToken.sol (0.8.24)

To learn more, run the command again with --verbose

Read about compiler configuration at https://hardhat.org/config


For more info go to https://hardhat.org/HH606 or run Hardhat with --show-stack-traces
```

**Comment by Paul-Sizon** [comment]
Hello, @escottalexander , thanks for the review. I fixed dependency issue, and added additional info about changing solidity compiler in README. I think it's possible to update template in order to pass other compiler version
